version: '3'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:3000 -t public
        environment:
            docker: "true"
        ports:
            - 3000:3000
        expose:
          - 3000
        volumes:
            - ./boats-service:/var/www
            - ./boats-service/logs:/var/www/logs
        networks:
            - my-network
    web-service:
        build: ./web
        ports:
            - "8080:80"
        expose:
          - "80"
        volumes:
            - ./web:/web
        networks:
          - my-network
networks:
    my-network:
